#!/bin/bash
if [ ! -f /usr/local/bin/deleteduser ]; then
    echo "echo "LOWCLASS"" > /usr/local/bin/deleteduser
	chmod +x /usr/local/bin/deleteduser
fi
hariini=`date +%d-%m-%Y`
clear
echo -e ""
echo -e "   FAST VPN OCSPANEL-INFO"
echo -e "=========-account-=========="
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
       do
       tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
       username=`echo $tuserval | cut -f1 -d:`
       userexp=`echo $tuserval | cut -f2 -d:`
       userexpireinseconds=$(( $userexp * 86400 ))
       tglexp=`date -d @$userexpireinseconds`             
       tgl=`echo $tglexp |awk -F" " '{print $3}'`
       while [ ${#tgl} -lt 2 ]
       do
           tgl="0"$tgl
       done
       while [ ${#username} -lt 15 ]
       do
           username=$username" " 
       done
       bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
       echo "echo "OCSPANEL User : $username หมดอายุ : $tgl $bulantahun"" >> /usr/local/bin/alluser
       todaystime=`date +%s`
       if [ $userexpireinseconds -ge $todaystime ] ;
           then
			:ไม่มีบัญชีที่หมดอายุ 
       else
       echo "echo "OCSPANEL & Username : $username หมดอายุ : $tgl $bulantahun ลบเรียบรอยแล้ว : $hariini "" >> /usr/local/bin/deleteduser
	   echo "Username $username ลบเรียบรอยแล้ว $hariini"
       userdel $username
       fi
done
echo -e ""
echo -e "============================"
echo -e "       LOWCLASS VPN"
echo -e ""
